Define TCR Assay file facets groups
CIMAC-CIDC/cidc-api-gae pull request #316
Opened 2020-10-14 15:42 UTC by roshni-b

Add facets for TCR assay data files

2020-10-14 16:11 UTC, roshni-b commented on cidc_api/models/files/facets.py
> +        ),
Not sure whether the sample sheet should be accessible by the file browser, hence not adding a facet group atm

2020-10-14 18:13 UTC, curlup requested changes

2020-10-14 18:13 UTC, curlup commented on cidc_api/models/files/facets.py
> +                "/tcr/r1.fastq.gz",
I don't think that's how facets will look like. There's a code that converts gcs uris into those, please check it out.

2020-10-14 18:13 UTC, curlup commented on cidc_api/models/files/details.py
> +    "/tcr/i2.fastq.gz": FileDetails("source"),
same as the other comment

2020-10-19 15:56 UTC, curlup approved these changes

2020-10-19 16:04 UTC, merged